package at.blvckbytes.component_markup.xml;

public enum ParseError {
  UNTERMINATED_INTERPOLATION,
  UNTERMINATED_STRING,
  UNTERMINATED_SUBTREE,
  UNTERMINATED_TAG,
  UNESCAPED_CLOSING_CURLY,
  MALFORMED_NUMBER,
  MALFORMED_LITERAL_TRUE,
  MALFORMED_LITERAL_FALSE,
  UNSUPPORTED_ATTRIBUTE_VALUE,
  MISSING_TAG_NAME,
  EXPECTED_ATTRIBUTE_KEY
}
