package at.blvckbytes.component_markup.xml;

public enum ParseError {
  UNTERMINATED_INTERPOLATION,
  UNTERMINATED_STRING,
  UNTERMINATED_SUBTREE,
  UNTERMINATED_TAG,
  MALFORMED_NUMBER,
  MALFORMED_LITERAL_TRUE,
  MALFORMED_LITERAL_FALSE,
  MALFORMED_LITERAL_NULL,
  UNSUPPORTED_ATTRIBUTE_VALUE,
  MISSING_TAG_NAME,
  MISSING_ATTRIBUTE_EQUALS,
}
