package at.blvckbytes.component_markup.expression.parser;

public enum ExpressionParserError {
  EXPECTED_EOS,
  EXPECTED_SUBSTRING_CLOSING_BRACKET,
  EXPECTED_SUBSCRIPT_CLOSING_BRACKET,
  EXPECTED_SUBSTRING_UPPER_BOUND,
  EXPECTED_RIGHT_INFIX_OPERAND,
  EXPECTED_PREFIX_OPERAND,
  EXPECTED_BRANCH_DELIMITER,
  EXPECTED_FALSE_BRANCH,
  EXPECTED_ARRAY_ITEM,
  EXPECTED_ARRAY_CLOSING_BRACKET,
  EXPECTED_PARENTHESES_CONTENT,
  EXPECTED_CLOSING_PARENTHESIS,
  EXPECTED_MEMBER_ACCESS_IDENTIFIER_RHS,
}
