package at.blvckbytes.component_markup.markup.parser.token;

public enum TokenType {
  ANY__WHITESPACE,

  MARKUP__COMMENT,
  MARKUP__PLAIN_TEXT,
  MARKUP__PUNCTUATION__TAG,
  MARKUP__PUNCTUATION__SUBTREE,
  MARKUP__PUNCTUATION__BINDING_SEPARATOR,
  MARKUP__PUNCTUATION__EQUALS,
  MARKUP__INTERPOLATION,
  MARKUP__STRING,
  MARKUP__NUMBER,
  MARKUP__IDENTIFIER__TAG,
  MARKUP__IDENTIFIER__ATTRIBUTE_USER,
  MARKUP__IDENTIFIER__ATTRIBUTE_INTRINSIC,
  MARKUP__IDENTIFIER__BINDING,
  MARKUP__OPERATOR__SPREAD,
  MARKUP__OPERATOR__NEGATE,
  MARKUP__OPERATOR__INTRINSIC_LITERAL,
  MARKUP__OPERATOR__INTRINSIC_EXPRESSION,
  MARKUP__OPERATOR__DYNAMIC_ATTRIBUTE,
  MARKUP__OPERATOR__CAPTURE,

  EXPRESSION__PUNCTUATION__ANY,
  EXPRESSION__LITERAL,
  EXPRESSION__STRING,
  EXPRESSION__NUMBER,
  EXPRESSION__IDENTIFIER_ANY,
  EXPRESSION__OPERATOR__ANY,
}
