package at.blvckbytes.component_markup.parser;

public enum AstParseError {
  UNKNOWN_TAG,
  UNKNOWN_ATTRIBUTE,
  UNKNOWN_STRUCTURAL_ATTRIBUTE,
  UNNAMED_LET_BINDING,
  UNNAMED_FOR_LOOP,
  BINDING_IN_USE,
  MALFORMED_IDENTIFIER,
  UNBALANCED_ATTRIBUTE_BRACKETS,
  UNBALANCED_CLOSING_TAG,
  NON_STRING_STRUCTURAL_ATTRIBUTE,
  NON_STRING_EXPRESSION_ATTRIBUTE,
  NON_STRING_LET_ATTRIBUTE,
  EXPECTED_SUBTREE_VALUE,
  EXPECTED_SCALAR_VALUE,
  EXPECTED_SELF_CLOSING_TAG,
  EXPECTED_OPEN_CLOSE_TAG,
  EXPECTED_STRUCTURAL_ATTRIBUTE_VALUE,
  EXPECTED_STRUCTURAL_ATTRIBUTE_FLAG,
  MULTIPLE_NON_MULTI_ATTRIBUTE,
  MULTIPLE_CONDITIONS,
  MULTIPLE_LOOPS,
  MISSING_PRECEDING_IF_SIBLING
}
