/*
 * Copyright (c) 2025, BlvckBytes
 * SPDX-License-Identifier: MIT
 */

package at.blvckbytes.component_markup.platform;

public enum PlatformFeature {
  KEY_COMPONENT,
  TRANSLATE_COMPONENT,
  CHANGE_PAGE_ACTION,
  COPY_TO_CLIPBOARD_ACTION,
  OPEN_FILE_ACTION,
  OPEN_URL_ACTION,
  RUN_COMMAND_ACTION,
  SUGGEST_COMMAND_ACTION,
  HOVER_ITEM_ACTION,
  HOVER_TEXT_ACTION,
  HOVER_ENTITY_ACTION,
  INSERT_ACTION,
  COLOR,
  SHADOW_COLOR,
  FONT,
  OBFUSCATED_FORMAT,
  BOLD_FORMAT,
  STRIKETHROUGH_FORMAT,
  UNDERLINED_FORMAT,
  ITALIC_FORMAT,
}
